.\" 42sh - A 42 school project
.TH man 42 "22 Nov 2017" "1.0"
.SH NAME
42sh \- The return of the Vengeance from the past!
.SH SYNOPSIS
42sh [options] [file]
.SH DESCRIPTION
42sh is an sh-compatible command language interpreter that executes commands read from the standard input or from a file.
.SH OPTIONS
.PP
-h		 Displays usage
.PP
--		 A -- signalas end of option
.SH SEE ALSO
21sh(1), minishell(1)
.SH AUTHORS
Giacomo Guiulfo
gguiulfo@student.42.us.org

Robin Schramm
rschramm@student.42.us.org

Akinfemi Akinaluko
aakin-al@student.42.us.org
